project:
  type: website

website:
  title: "Data Parties"
  subtitle: "(and other things I won't shut up about)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: talks.qmd
        text: Talks
      - href: blog.qmd
        text: Musings

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



