project:
  type: website

website:
  title: "Data Parties"
  subtitle: "(and other things I won't shut up about)"
  navbar:
    right:
      - href: about.qmd
        text: about
      - href: talks.qmd
        text: talks
      - href: blog.qmd
        text: musings
      - href: reading.qmd
        text: reading
      - href: experimental.qmd
        text: experimental

format:
  html:
    theme: 
      - litera
      - styles.scss
    toc: true



