project:
  type: website

execute:
  freeze: auto
  
website:
  title: "Data Parties"
  #subtitle: "(and other things I won't shut up about)"
  google-analytics: "G-WM3Q5HHPPE"
  navbar:
    right:
      - href: about.qmd
        text: about
      - href: talks.qmd
        text: talks
      - href: portfolio.qmd
        text: portfolio
      - href: blog.qmd
        text: musings
      - href: reading.qmd
        text: reading
      - href: experimental.qmd
        text: experimental

format:
  html:
    theme: 
      - litera
      - styles.scss
    toc: true



